# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B59CDB
background         #010103
cursor             #8A6D9F

active_tab_foreground     #010103
active_tab_background     #B59CDB
inactive_tab_foreground   #B59CDB
inactive_tab_background   #010103

active_border_color   #B59CDB
inactive_border_color #010103
bell_border_color     #683839

color0      #010104
color1		#683839
color2		#354271
color3		#3E3078
color4		#6F302C
color5		#5F3D62
color6		#523C73
color7		#9C84C1
color8		#6C568F
color9		#683839
color10		#354271
color11		#3E3078
color12		#6F302C
color13		#5F3D62
color14		#523C73
color15		#C5B9D7
